import { esc } from '../../core/ui.js?v=20261008j';
import { ACTION_LABEL, ROLE_LABEL, KIND_LABEL, RESULT_LABEL, kstText } from './accesslog-logic.js?v=20261008j';

export function accessLogHtml(st) {
  const s = st.sum; const chk = st.check;
  const checkBox = chk ? '<div class="jh-alert" data-tone="info" role="status">✅ ' + esc(st.ym) + ' 점검 완료 — ' + esc(chk.checkedByName || '') + ' · ' + esc(chk.when || '') + (chk.note ? ' · ' + esc(chk.note) : '') + '</div>'
    : '<div class="jh-alog__check"><div class="jh-field__hint">' + esc(st.ym) + ' 열람 기록을 확인하셨으면 점검 완료로 표시해 두세요. (법정 월 1회 점검 — 누가·언제 확인했는지 남습니다)</div><div class="jh-alog__checkrow"><input class="jh-input" id="alog-note" maxlength="100" placeholder="메모(선택) 예: 이상 없음"><button type="button" class="jh-btn" data-variant="primary" data-alog-check>점검 완료 표시</button></div></div>';
  const flag = s.flagged.length ? '<div class="jh-alert" data-tone="warn" role="alert">⚠ 하루 조회가 많았던 경우: ' + s.flagged.slice(0, 5).map((f) => esc(f.name) + ' ' + esc(f.day.slice(5)) + ' ' + f.n + '건').join(' · ') + (s.flagged.length > 5 ? ' 외 ' + (s.flagged.length - 5) + '건' : '') + '</div>' : '';
  const actors = s.actors.length ? s.actors.slice(0, 8).map((a) => '<span class="jh-chip">' + esc(a.name) + ' ' + a.n + '건</span>').join('') : '<span class="jh-field__hint">이 달 기록이 없습니다.</span>';
  const opts = ['<option value="">전체 열람자</option>'].concat(st.actorOptions.map((a) => '<option value="' + esc(a.uid) + '"' + (st.filter.actor === a.uid ? ' selected' : '') + '>' + esc(a.name) + '</option>')).join('');
  const rows = st.list.length ? st.list.map((e) => '<div class="jh-card jh-alog__row"' + (e.result === 'error' ? ' data-bad="true"' : '') + '><span class="jh-alog__time">' + esc(kstText(e.ms)) + '</span><span class="jh-alog__who"><strong>' + esc(e.actorName || '-') + '</strong> <span class="jh-field__hint">' + esc(ROLE_LABEL[e.role] || e.role || '') + '</span></span><span class="jh-alog__what">' + esc(ACTION_LABEL[e.action] || e.action) + (e.reason ? ' · ' + esc(e.reason) : '') + '</span><span class="jh-alog__target">' + esc(e.targetName || (e.workerId && e.workerId !== '(전체)' ? e.workerId : '')) + ' <span class="jh-field__hint">' + esc(KIND_LABEL[e.kind] || e.kind || '') + '</span></span><span class="jh-alog__ip jh-field__hint">' + esc(e.ip || '') + (e.result && e.result !== 'ok' ? ' · ' + esc(RESULT_LABEL[e.result] || e.result) : '') + '</span></div>').join('') : '<div class="jh-empty">조건에 맞는 기록이 없습니다.</div>';
  return '<div class="jh-alog"><div class="jh-staff__bar"><div class="jh-segmented" role="group" aria-label="월 선택"><button type="button" class="jh-btn" data-variant="ghost" data-alog-month="-1">‹ 이전 달</button><span class="jh-alog__ym">' + esc(st.ym) + '</span><button type="button" class="jh-btn" data-variant="ghost" data-alog-month="1"' + (st.ym >= st.maxYm ? ' disabled' : '') + '>다음 달 ›</button></div></div>' +
    '<p class="jh-field__hint">주민(외국인)등록번호를 누가·언제·누구의 것·어떤 사유로 조회·저장했는지 서버가 남긴 기록입니다. 기록은 3년간 보관되며 수정·삭제할 수 없습니다.</p>' + checkBox + flag +
    '<div class="jh-card jh-form"><div class="jh-alog__sum"><strong>이 달 ' + s.total + '건</strong> <span class="jh-field__hint">(조회 ' + s.reveals + '건)</span></div><div class="jh-alog__chips">' + actors + '</div></div>' +
    '<div class="jh-alog__filters"><select class="jh-input" data-alog-actor aria-label="열람자">' + opts + '</select><select class="jh-input" data-alog-action aria-label="종류"><option value="">조회·변경 전체</option><option value="reveal"' + (st.filter.action === 'reveal' ? ' selected' : '') + '>조회만</option><option value="other"' + (st.filter.action === 'other' ? ' selected' : '') + '>저장·이전 등</option></select><input class="jh-input" data-alog-q placeholder="대상 이름 검색" value="' + esc(st.filter.q || '') + '"></div>' +
    '<div class="jh-alog__list">' + rows + '</div>' + (st.truncated ? '<p class="jh-field__hint">최근 500건까지만 보여 줍니다. 열람자·종류로 좁혀 보세요.</p>' : '') + '</div>';
}
